# Generated by Django 5.2.8 on 2025-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Enter Student Name', max_length=20)),
                ('age', models.IntegerField(help_text='Enter Student Age')),
                ('dob', models.DateField()),
                ('reg_no', models.IntegerField(help_text='Enter the Registration Nimber')),
            ],
        ),
    ]
