# Generated by Django 5.2.8 on 2025-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=30)),
                ('phone_number', models.CharField(help_text='Enter Phone Number', max_length=15)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
